SELECT * FROM customerBehaviour..customer

--What is the total revenue generated by male vs female customer

SELECT gender, SUM(purchase_amount) total_revenue
FROM customer
GROUP BY gender
ORDER BY SUM(purchase_amount) DESC

--Which customers used a discount but still spent more than the average purchase amount
SELECT customer_id, purchase_amount
FROM customer
WHERE discount_applied = 'Yes' 
AND purchase_amount >= (SELECT AVG(purchase_amount) FROM customer)

--Which are the top 5 products with the highest average review rating
SELECT TOP 5 item_purchased, ROUND(AVG(review_rating), 2) Avg_Review_Rating
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC

--Compare the average purchase amounts between standard and express shipping
SELECT shipping_type, ROUND(AVG(purchase_amount), 2) Avg_purchase_amount
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type
ORDER BY AVG(purchase_amount) DESC

--Do subscribed customers spend more? Compare average spend and total revenue
--between subscribers and non-subscribers
SELECT 
    subscription_status, 
    COUNT(customer_id) total_customer, 
    ROUND(AVG(purchase_amount), 2) avg_spend, 
    SUM(purchase_amount) total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue, avg_spend DESC

--Which 5 product have the highest percentage of purchase with discount_applied
SELECT TOP 5 item_purchased, 
ROUND(100 * SUM(
    CASE WHEN discount_applied = 'Yes' THEN 1
    ELSE 0 END
)/COUNT(*), 2) discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC

--Segment customers into New, Returning, and Loyal based on their total
--number of previous purchases, and show the count of each segment

with customer_type as (
SELECT customer_id,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE  'Loyal'
END customer_status
FROM customer)

SELECT customer_type.customer_status, COUNT(customer_status) no_customer_status
FROM customer_type
GROUP BY customer_type.customer_status
order by no_customer_status DESC

--What are the top 3 most purchased products within each category
WITH items_count as (
SELECT
category, item_purchased,
COUNT(customer_id) as total_orders,
ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) items_rank
FROM customer
GROUP BY category, item_purchased
)

SELECT 
    items_rank, 
    category, 
    item_purchased, 
    total_orders
FROM items_count
WHERE items_rank <= 3

--Are customers who are repeat buyers (more than 5 previous purchases) 
--also likely to subscribe?
SELECT
    subscription_status,
    count(customer_id) repeat_buyers
FROM 
    customer
WHERE previous_purchases > 5
GROUP BY subscription_status
ORDER BY repeat_buyers DESC

--What is the revenue contributed of each age-group
SELECT
    age_group,
    SUM(purchase_amount) total_revenue
FROM
    customer
GROUP BY age_group
ORDER BY total_revenue DESC